;
; File generated by cc65 v 2.19 - Git 4680d68e5
;
	.fopt		compiler,"cc65 v 2.19 - Git 4680d68e5"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_midi_init
	.import		_midi_start_transmission
	.import		_midi_flush
	.export		_midi_send_byte
	.export		_midi_send_buffer
	.export		_midi_buffer_free
	.export		_midi_note_on
	.export		_midi_note_off
	.export		_midi_program_change
	.export		_midi_control_change
	.export		_midi_pitch_bend
	.export		_midi_all_notes_off
	.export		_midi_all_sound_off
	.export		_midi_reset_controllers
	.import		_midi_buffer
	.import		_midi_head
	.import		_midi_tail
	.import		_midi_tx_state
	.export		_main

.segment	"RODATA"

_c_major_scale:
	.byte	$3c
	.byte	$3e
	.byte	$40
	.byte	$41
	.byte	$43
	.byte	$45
	.byte	$47
	.byte	$48

; ---------------------------------------------------------------
; unsigned char __near__ midi_send_byte (unsigned char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_send_byte: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	lda     _midi_head
	ina
	and     #$3F
	ldy     #$01
	sta     (c_sp),y
	cmp     _midi_tail
	bne     L0003
	ldx     #$00
	tya
	jmp     incsp3
L0003:	php
	sei
	iny
	lda     (c_sp),y
	ldy     _midi_head
	sta     _midi_buffer,y
	ldy     #$01
	lda     (c_sp),y
	sta     _midi_head
	lda     _midi_tx_state
	sta     (c_sp)
	plp
	ldx     #$00
	lda     (c_sp)
	bne     L0007
	jsr     _midi_start_transmission
	ldx     #$00
L0007:	txa
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ midi_send_buffer (const unsigned char *data, unsigned char len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_send_buffer: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	lda     #$00
	sta     (c_sp)
	ldy     #$01
L0007:	sta     (c_sp),y
	iny
	cmp     (c_sp),y
	bcs     L0003
	ldy     #$04
	jsr     ldptr1ysp
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     (ptr1),y
	jsr     _midi_send_byte
	cmp     #$00
	bne     L0003
	clc
	ina
	adc     (c_sp)
	sta     (c_sp)
	ldy     #$01
	clc
	tya
	adc     (c_sp),y
	bra     L0007
L0003:	ldx     #$00
	lda     (c_sp)
	jmp     incsp5

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ midi_buffer_free (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_buffer_free: near

.segment	"CODE"

	jsr     decsp3
	php
	sei
	lda     _midi_head
	ldy     #$02
	sta     (c_sp),y
	lda     _midi_tail
	dey
	sta     (c_sp),y
	plp
	iny
	lda     (c_sp),y
	dey
	cmp     (c_sp),y
	bcc     L0007
	iny
	lda     (c_sp),y
	sec
	dey
	sbc     (c_sp),y
	bra     L0008
L0007:	lda     #$40
	sec
	sbc     (c_sp),y
	sta     ptr1
	iny
	lda     (c_sp),y
	clc
	adc     ptr1
L0008:	sta     (c_sp)
	lda     #$3F
	sec
	sbc     (c_sp)
	ldx     #$00
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ midi_note_on (unsigned char channel, unsigned char note, unsigned char velocity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_note_on: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	and     #$0F
	ora     #$90
	jsr     _midi_send_byte
	ldy     #$01
	lda     (c_sp),y
	and     #$7F
	jsr     _midi_send_byte
	lda     (c_sp)
	and     #$7F
	jsr     _midi_send_byte
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ midi_note_off (unsigned char channel, unsigned char note, unsigned char velocity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_note_off: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	and     #$0F
	ora     #$80
	jsr     _midi_send_byte
	ldy     #$01
	lda     (c_sp),y
	and     #$7F
	jsr     _midi_send_byte
	lda     (c_sp)
	and     #$7F
	jsr     _midi_send_byte
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ midi_program_change (unsigned char channel, unsigned char program)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_program_change: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	and     #$0F
	ora     #$C0
	jsr     _midi_send_byte
	lda     (c_sp)
	and     #$7F
	jsr     _midi_send_byte
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ midi_control_change (unsigned char channel, unsigned char controller, unsigned char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_control_change: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	lda     (c_sp),y
	and     #$0F
	ora     #$B0
	jsr     _midi_send_byte
	ldy     #$01
	lda     (c_sp),y
	and     #$7F
	jsr     _midi_send_byte
	lda     (c_sp)
	and     #$7F
	jsr     _midi_send_byte
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ midi_pitch_bend (unsigned char channel, unsigned int value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_pitch_bend: near

.segment	"CODE"

	jsr     pushax
	ldy     #$02
	lda     (c_sp),y
	and     #$0F
	ora     #$E0
	jsr     _midi_send_byte
	lda     (c_sp)
	and     #$7F
	jsr     _midi_send_byte
	jsr     ldax0sp
	jsr     shrax7
	and     #$7F
	jsr     _midi_send_byte
	jmp     incsp3

.endproc

; ---------------------------------------------------------------
; void __near__ midi_all_notes_off (unsigned char channel)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_all_notes_off: near

.segment	"CODE"

	jsr     pusha
	lda     (c_sp)
	jsr     pusha
	lda     #$7B
	jsr     pusha
	lda     #$00
	jsr     _midi_control_change
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ midi_all_sound_off (unsigned char channel)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_all_sound_off: near

.segment	"CODE"

	jsr     pusha
	lda     (c_sp)
	jsr     pusha
	lda     #$78
	jsr     pusha
	lda     #$00
	jsr     _midi_control_change
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ midi_reset_controllers (unsigned char channel)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_reset_controllers: near

.segment	"CODE"

	jsr     pusha
	lda     (c_sp)
	jsr     pusha
	lda     #$79
	jsr     pusha
	lda     #$00
	jsr     _midi_control_change
	jmp     incsp1

.endproc

; ---------------------------------------------------------------
; void __near__ delay_ms (unsigned int ms)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay_ms: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	ldx     #$00
	txa
	ldy     #$02
	jsr     staxysp
L0002:	ldy     #$03
	jsr     ldaxysp
	ldy     #$04
	cmp     (c_sp),y
	txa
	iny
	sbc     (c_sp),y
	bcs     L0003
	ldx     #$00
	txa
	jsr     stax0sp
L0006:	ldy     #$01
	lda     (c_sp),y
	cmp     #$00
	bne     L000A
	lda     (c_sp)
	cmp     #$C8
L000A:	bcs     L0004
	nop
	nop
	nop
	nop
	ldx     #$00
	tya
	jsr     addeq0sp
	bra     L0006
L0004:	iny
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	bra     L0002
L0003:	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	jsr     _midi_init
	ldx     #$00
	lda     #$64
	jsr     _delay_ms
	lda     #$00
	jsr     pusha
	jsr     _midi_program_change
	lda     #$00
	jsr     pusha
	lda     #$07
	jsr     pusha
	lda     #$64
	jsr     _midi_control_change
L0002:	lda     #$00
L000B:	sta     (c_sp)
	cmp     #$08
	bcs     L0006
	lda     #$00
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     _c_major_scale,y
	jsr     pusha
	lda     #$50
	jsr     _midi_note_on
	ldx     #$00
	lda     #$96
	jsr     _delay_ms
	lda     #$00
	jsr     pusha
	ldy     #$01
	lda     (c_sp),y
	tay
	lda     _c_major_scale,y
	jsr     pusha
	lda     #$00
	jsr     _midi_note_off
	ldx     #$00
	lda     #$14
	jsr     _delay_ms
	clc
	lda     #$01
	adc     (c_sp)
	bra     L000B
L0006:	jsr     _midi_flush
	ldx     #$01
	lda     #$F4
	jsr     _delay_ms
	bra     L0002

.endproc

