/* --- ANSI Color Macros --- */
#define ANSI_CLS        "\x1b[2J\x1b[H"
#define ANSI_RESET      "\x1b[0m"
#define ANSI_BOLD       "\x1b[1m"
#define ANSI_CYAN       "\x1b[36m"
#define ANSI_GREEN      "\x1b[32m"
#define ANSI_YELLOW     "\x1b[33m"
#define ANSI_WHITE      "\x1b[37m"
#define ANSI_MAGENTA    "\x1b[35m"
#define ANSI_RED        "\x1b[31m"
#define ANSI_DARK_GRAY  "\x1b[90m"
