#define CSI_ESC "\x1b"
#define CSI CSI_ESC "["
#define CSI_RESET       CSI_ESC "c"
#define CSI_CLS         CSI "2J"
#define CSI_CURSOR_SHOW CSI "?25h"
#define CSI_CURSOR_HIDE CSI "?25l"
#define CSI_CURSOR_AT   CSI "n20;m15H"
