;
; File generated by cc65 v 2.19 - Git 4680d68e5
;
	.fopt		compiler,"cc65 v 2.19 - Git 4680d68e5"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_midi_init
	.import		_midi_start_transmission
	.import		_midi_flush
	.export		_midi_send_byte
	.export		_midi_send_buffer
	.export		_midi_buffer_free
	.export		_midi_note_on
	.export		_midi_note_off
	.export		_midi_program_change
	.export		_midi_control_change
	.export		_midi_pitch_bend
	.export		_midi_all_notes_off
	.import		_midi_buffer
	.importzp	_midi_head
	.importzp	_midi_tail
	.importzp	_midi_tx_state
	.export		_main

.segment	"RODATA"

_scale:
	.byte	$3c
	.byte	$3e
	.byte	$40
	.byte	$41
	.byte	$43
	.byte	$45
	.byte	$47
	.byte	$48

; ---------------------------------------------------------------
; unsigned char __near__ midi_send_byte (unsigned char data)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_send_byte: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldx     #$00
	lda     _midi_head
	ina
	bne     L0002
	inx
L0002:	ldx     #$00
	and     #$3F
	ldx     #$00
	ldy     #$01
	sta     (c_sp),y
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldx     #$00
	lda     _midi_tail
	jsr     toseqax
	jeq     L0003
	ldx     #$00
	lda     #$01
	jmp     L0001
L0003:	sei
	lda     #<(_midi_buffer)
	ldx     #>(_midi_buffer)
	clc
	adc     _midi_head
	bcc     L0004
	inx
L0004:	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	ldy     #$00
	jsr     staspidx
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	sta     _midi_head
	ldx     #$00
	lda     _midi_tx_state
	ldy     #$00
	sta     (c_sp),y
	cli
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     booleq
	jeq     L0005
	jsr     _midi_start_transmission
L0005:	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ midi_send_buffer (const unsigned char *data, unsigned char len)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_send_buffer: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp2
	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (c_sp),y
	ldx     #$00
	lda     #$00
	ldy     #$01
	sta     (c_sp),y
L0002:	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     tosultax
	jne     L0005
	jmp     L0003
L0005:	ldy     #$04
	jsr     ldaxysp
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     tosaddax
	ldy     #$00
	jsr     ldauidx
	jsr     _midi_send_byte
	cmp     #$00
	jsr     boolne
	jeq     L0006
	jmp     L0003
L0006:	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	ldy     #$01
	ldx     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	jmp     L0002
L0003:	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jmp     L0001
L0001:	jsr     incsp5
	rts

.endproc

; ---------------------------------------------------------------
; unsigned char __near__ midi_buffer_free (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_buffer_free: near

.segment	"CODE"

	jsr     decsp3
	sei
	ldx     #$00
	lda     _midi_head
	ldy     #$02
	sta     (c_sp),y
	ldx     #$00
	lda     _midi_tail
	ldy     #$01
	sta     (c_sp),y
	cli
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     tosugeax
	jeq     L0002
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     tossubax
	ldx     #$00
	ldy     #$00
	sta     (c_sp),y
	jmp     L0003
L0002:	ldx     #$00
	lda     #$40
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	jsr     tossubax
	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	jsr     tosaddax
	ldx     #$00
	ldy     #$00
	sta     (c_sp),y
L0003:	ldx     #$00
	lda     #$3F
	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	jsr     tossubax
	ldx     #$00
	jmp     L0001
L0001:	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_note_on (unsigned char channel, unsigned char note, unsigned char velocity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_note_on: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	ora     #$90
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_note_off (unsigned char channel, unsigned char note, unsigned char velocity)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_note_off: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	ora     #$80
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_program_change (unsigned char channel, unsigned char program)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_program_change: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	ora     #$C0
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	jsr     incsp2
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_control_change (unsigned char channel, unsigned char controller, unsigned char value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_control_change: near

.segment	"CODE"

	jsr     pusha
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	ora     #$B0
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_pitch_bend (unsigned char channel, unsigned int value)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_pitch_bend: near

.segment	"CODE"

	jsr     pushax
	ldy     #$02
	ldx     #$00
	lda     (c_sp),y
	ldx     #$00
	and     #$0F
	ora     #$E0
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$01
	jsr     ldaxysp
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	ldy     #$01
	jsr     ldaxysp
	jsr     shrax7
	ldx     #$00
	and     #$7F
	ldx     #$00
	jsr     _midi_send_byte
	jsr     incsp3
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ midi_all_notes_off (unsigned char channel)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_midi_all_notes_off: near

.segment	"CODE"

	jsr     pusha
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	jsr     pusha
	ldx     #$00
	lda     #$7B
	jsr     pusha
	ldx     #$00
	lda     #$00
	jsr     _midi_control_change
	jsr     incsp1
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ delay_ms (unsigned int ms)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_delay_ms: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp4
	ldx     #$00
	lda     #$00
	ldy     #$02
	jsr     staxysp
L0002:	ldy     #$03
	jsr     ldaxysp
	jsr     pushax
	ldy     #$07
	jsr     ldaxysp
	jsr     tosultax
	jne     L0005
	jmp     L0003
L0005:	ldx     #$00
	lda     #$00
	ldy     #$00
	jsr     staxysp
L0006:	ldy     #$01
	jsr     ldaxysp
	cpx     #$03
	bne     L000A
	cmp     #$20
L000A:	jsr     boolult
	jne     L0009
	jmp     L0004
L0009:	nop
	ldy     #$00
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0006
L0004:	ldy     #$02
	ldx     #$00
	lda     #$01
	jsr     addeqysp
	jmp     L0002
L0003:	jsr     incsp6
	rts

.endproc

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	jsr     decsp1
	jsr     _midi_init
	ldx     #$00
	lda     #$64
	jsr     _delay_ms
	ldx     #$00
	lda     #$00
	jsr     pusha
	ldx     #$00
	lda     #$00
	jsr     _midi_program_change
	ldx     #$00
	lda     #$00
	jsr     pusha
	ldx     #$00
	lda     #$07
	jsr     pusha
	ldx     #$00
	lda     #$64
	jsr     _midi_control_change
L0002:	jmp     L0005
L0004:	jmp     L0002
L0005:	ldx     #$00
	lda     #$00
	ldy     #$00
	sta     (c_sp),y
L0006:	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$08
	jsr     boolult
	jne     L0009
	jmp     L0007
L0009:	ldx     #$00
	lda     #$00
	jsr     pusha
	lda     #<(_scale)
	ldx     #>(_scale)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L000A
	inx
L000A:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	ldx     #$00
	lda     #$50
	jsr     _midi_note_on
	ldx     #$00
	lda     #$96
	jsr     _delay_ms
	ldx     #$00
	lda     #$00
	jsr     pusha
	lda     #<(_scale)
	ldx     #>(_scale)
	ldy     #$01
	clc
	adc     (c_sp),y
	bcc     L000B
	inx
L000B:	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	ldx     #$00
	lda     #$00
	jsr     _midi_note_off
	ldx     #$00
	lda     #$1E
	jsr     _delay_ms
	ldy     #$00
	ldx     #$00
	clc
	lda     #$01
	adc     (c_sp),y
	sta     (c_sp),y
	jmp     L0006
L0007:	ldx     #$00
	lda     #$08
	ldy     #$00
	sta     (c_sp),y
L000C:	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	cmp     #$00
	jsr     boolne
	jne     L000F
	jmp     L000D
L000F:	ldx     #$00
	lda     #$00
	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	clc
	adc     #<(_scale)
	tay
	txa
	adc     #>(_scale)
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	ldx     #$00
	lda     #$50
	jsr     _midi_note_on
	ldx     #$00
	lda     #$96
	jsr     _delay_ms
	ldx     #$00
	lda     #$00
	jsr     pusha
	ldy     #$01
	ldx     #$00
	lda     (c_sp),y
	jsr     decax1
	clc
	adc     #<(_scale)
	tay
	txa
	adc     #>(_scale)
	tax
	tya
	ldy     #$00
	jsr     ldauidx
	jsr     pusha
	ldx     #$00
	lda     #$00
	jsr     _midi_note_off
	ldx     #$00
	lda     #$1E
	jsr     _delay_ms
	ldy     #$00
	ldx     #$00
	lda     (c_sp),y
	sec
	sbc     #$01
	sta     (c_sp),y
	jmp     L000C
L000D:	jsr     _midi_flush
	ldx     #$01
	lda     #$F4
	jsr     _delay_ms
	jmp     L0004
	rts

.endproc

